// These styles apply to every route in the application
import "./globals.css";
import type { Metadata } from "next";
import { ThemeProvider } from "next-themes";
import { Poppins, Inconsolata } from "next/font/google";

const poppins = Poppins({
  weight: "400",
  variable: "--body-poppins",
  subsets: ["latin"],
});

const inconsolata = Inconsolata({
  weight: "400",
  variable: "--body-inconsolata",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <head>
        {/* <meta name="viewport" content="width=device-width, initial-scale=1.0" /> */}
      </head>
      <body className={`${poppins.variable} ${inconsolata.variable} overscroll-x-none`}>
        {children}
      </body>
    </html>
  );
}
